[build]
  base = "/frontend/steam-comments"
  publish = "/dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  to = "/.netlify/functions/comments" 
  from = "/api/*" 
  status = 200