[build]
  # base = "/steam-comments"
  # publish = "/dist"
  command = "npm run build"

# [functions]
#   directory = "../netlify/functions"

[[redirects]]
  to = "/.netlify/functions/comments" 
  from = "/api/*" 
  status = 200